#### Numpy

NumPy (short for Numerical Python) is a powerful open-source Python library used for numerical computing. It provides:

Core Features:
N-dimensional arrays (ndarray): Efficient, fast arrays for storing and manipulating large datasets.

Mathematical operations: Vectorized operations (element-wise) on arrays, which are much faster than using Python loops.

Broadcasting: Ability to perform arithmetic operations on arrays of different shapes.

Linear algebra, statistics, and Fourier transforms: Built-in support for complex mathematical functions.

Random number generation: Tools for creating random data for simulations and testing.

Integration with C/C++ and Fortran: High performance and easy interoperability with lower-level code.

In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5,6],
                [1,2,3,4,5,6],
                [1,2,3,4,5,6],
                [1,2,3,4,5,6]])
print(arr)
# shape
print(arr.shape)
# arange
np.arange(0,10,2).reshape(5,1)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
(4, 6)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [2]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
arr = np.array([[1,2,3],[1,2,3]])

print("Array: \n", arr)
print("Shape:", arr.shape)
print("Number of dimenstions:", arr.ndim)
print("Size (number of elements)", arr.size)
print("Data type:", arr.dtype)
print("Item size:", arr.itemsize)

Array: 
 [[1 2 3]
 [1 2 3]]
Shape: (2, 3)
Number of dimenstions: 2
Size (number of elements) 6
Data type: int64
Item size: 8


In [10]:
# numpy vectorized operations
arr1 = np.array([10,11,12,13,14])
arr2 = np.array([1,2,3,4,5])

# Element wise add
print("Addition:", arr1 + arr2)

# Element wise sub
print("Substraction:", arr1 - arr2)

# Element wie multiplication
print("Multiplication:", arr1 * arr2)

# Element wise division
print("Division:", arr1 / arr2)

# Element wise modulus
print("Modulus:", arr1 % arr2)


Addition: [11 13 15 17 19]
Substraction: [9 9 9 9 9]
Multiplication: [10 22 36 52 70]
Division: [10.    5.5   4.    3.25  2.8 ]
Modulus: [0 1 0 1 4]


In [27]:
# Universal funtions
arr = np.array([4,9,16])
# sqrt
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# log
print(np.log(arr))

[2. 3. 4.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[-0.7568025   0.41211849 -0.28790332]
[1.38629436 2.19722458 2.77258872]


In [49]:
# Array slicing and indexing
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr)

print(arr[0][1])
print(arr[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[ 6  7]
 [10 11]]


In [55]:
# statistical concepts -- Normalization

data = np.array([1,2,4,3,5])

mean = np.mean(data)
standard_dev = np.std(data)
print("Mean:", mean)
print("Standard_dev:", standard_dev)
# normalize the data 
normalized_data = (data - mean) / standard_dev
print("Normalized data:", normalized_data)

# variance
variance = np.var(data)
print("Variance:", variance)

Mean: 3.0
Standard_dev: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.70710678  0.          1.41421356]
Variance: 2.0
